Add no tunnel flag to dev
Shopify/cli pull request #174
Opened 2022-07-20 09:17 UTC by alvaro-shopify

### WHY are these changes introduced?

Fixes https://github.com/Shopify/shopify-cli-planning/issues/319

An Ngrok tunnel is always created when using `dev` command. A new flag is needed to run the command `dev` without a tunnel exposing directly a localhost port.

Listening to localhost is now available after adding that option to web project Content Security Policy in this PR https://github.com/Shopify/web/pull/68866

### WHAT is this pull request doing?
- Added a new flag `--no-tunnel` to `dev` command. By default is disabled so an ngrok tunnel is automatically created if the flag is not used 
- In case using `--no-tunnel` extensions testing is failing because a validation is made by extensions binary` that checks the using of `localhost` or `:<local_port>``
<p align="center"><img width="400" alt="image"  src="https://user-images.githubusercontent.com/105213827/179944483-102bdfda-4c94-44ce-9c41-b3e43eea07b5.png"></p>
- No reverse proxy is used when `--no-tunnel` is used and there is no extensions

### How to test your changes?
- `yarn shopify app dev --no-tunnel --path <app_path>`

2022-07-20 09:50 UTC, shauns requested changes

2022-07-20 09:50 UTC, shauns commented on packages/app/src/cli/commands/app/dev.ts
> +        'Override the ngrok tunnel URL. Format: "https://my-tunnel-url:port". Has no effect in case of using --no-tunnel',
Can you revert the doc change. Let's keep `no-tunnel` quiet for now.

2022-07-20 09:50 UTC, shauns commented on packages/app/src/cli/commands/app/dev.ts
> +      hidden: false,
hidden should be true I think

2022-07-21 08:23 UTC, pepicrft reviewed
Correct me if I'm wrong, but assuming the following combinatory of flags is right:

| `--no-tunnel` | `--tunnel-url` | Valid | Behaviour |
| --- | --- | --- | -- |
| Passed | Not passed | Yes | Localhost |
| Passed | Passed | Yes | Localhost |
| Not passed | Not passed | Yes | Ngrok |
| Not passed | Passed | Yes | Passed URL |

I think there's an opportunity here to simplify things for the user. Here's a proposal:
```
shopify dev --public-url localhost
shopify dev --public-url tunnel
shopify dev --public-url https://your-own-url....
```

Since the above is a behaviour breaking change because users would have to go from `shopify dev` to `shopify dev --public-url tunnel`, we can keep the current behaviour but include a deprecation message that tells the user about the new workflow.

2022-07-21 12:01 UTC, pepicrft approved these changes

2022-07-21 12:16 UTC, merged