Import flow extensions command
Shopify/cli pull request #2249
Opened 2023-06-28 12:04 UTC by isaacroldan

### WHY are these changes introduced?

Fixes #0000 

### WHAT is this pull request doing?

### How to test your changes?

### Post-release steps

### Measuring impact

How do we know this change was effective? Please choose one:

- [ ] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible [documentation](https://shopify.dev) changes
- [ ] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

2023-06-28 12:09 UTC, isaacroldan commented on packages/app/src/cli/api/graphql/extension_migrate_flow_extension.ts
> +export const ExtensionMigrateFlowExtensionQuery = gql`
This is added here but not used yet until is ready on partners.

2023-06-28 16:21 UTC, ryanische approved these changes
Thank you!

2023-06-28 16:21 UTC, ryanische commented on packages/app/oclif.manifest.json
> +      "description": "Deploy your Shopify app.",
Looks like this needs to be updated.

2023-06-28 16:21 UTC, ryanische commented on packages/app/src/cli/commands/app/import-flow-legacy-extensions.ts
> +  static description = 'Deploy your Shopify app.'
Also needs updating.

2023-06-28 16:21 UTC, ryanische commented on packages/app/src/cli/services/import-flow/fetch.ts
> +    const isFLow = ext.type === 'flow_action_definition' || ext.type === 'flow_trigger_definition'
```suggestion
    const isFlow = ext.type === 'flow_action_definition' || ext.type === 'flow_trigger_definition'
```

2023-06-28 16:21 UTC, ryanische commented on packages/app/src/cli/services/import-flow/fetch.ts
> +    return isFLow && (hasActiveVersion || hasDraftVersion)
```suggestion
    return isFlow && (hasActiveVersion || hasDraftVersion)
```

2023-06-28 18:11 UTC, omnisyle approved these changes
LGTM

2023-06-29 00:13 UTC, MaxLeduc requested changes
Look awesome and works like a charm! Left a couple comments - including some critical changes to how we assign `uiType`. LMK if I can help you implement that!

2023-06-29 08:18 UTC, isaacroldan commented on packages/app/src/cli/commands/app/import-flow-legacy-extensions.ts
> +    'client-id': Flags.string({
clientID is the new name for apiKey, this flag allows you to pass a specific clientID in case you want to import from a specific app

2023-06-29 10:54 UTC, isaacroldan commented on packages/app/src/cli/services/flow/serialize-fields.test.ts
> +    expect(reSerializedFields).toEqual(fields)
@MaxLeduc Here i'm testing that parsing the partners fields, and then serializing them again produces the same result.

2023-06-29 10:54 UTC, isaacroldan commented on packages/app/src/cli/services/flow/serialize-fields.ts
> +    serializedField.label = `${capitalize(commerceObject)} ID`
This is what you wanted right?

2023-06-29 14:35 UTC, MaxLeduc approved these changes
LGTM! 🎉

2023-06-29 14:35 UTC, MaxLeduc commented on packages/app/src/cli/services/flow/serialize-fields.ts
> +    serializedField.label = `${capitalize(commerceObject)} ID`
Correct, thank you 🙏

2023-06-30 11:09 UTC, merged