Include all extension properties when loading unified toml file
Shopify/cli pull request #2470
Opened 2023-07-18 18:35 UTC by nsimone

### WHY are these changes introduced?

When using the configuration parsed with the UnifiedSchema, additional properties on the extensions were omitted (ex. Flow trigger fields).

### WHAT is this pull request doing?

This change uses the decoded toml file instead which includes those properties.

### How to test your changes?

1. Generate a Flow trigger extension + deploy
2. Check the `config` of the registration record or use the trigger in a Flow workflow - the `settings.fields` from the toml file should be available

### Measuring impact

How do we know this change was effective? Please choose one:

- [X] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [X] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [X] I've considered possible [documentation](https://shopify.dev) changes
- [X] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

2023-07-18 18:37 UTC, MaxLeduc approved these changes
🚀

2023-07-18 18:37 UTC, jenniferwills approved these changes

2023-07-19 10:49 UTC, isaacroldan requested changes
Discussed offline, let's explicitly add `settings` to UnifiedSchema :)

2023-07-19 13:59 UTC, davejcameron approved these changes

2023-07-19 14:27 UTC, merged