Added app id to retail mobile qr code
Shopify/cli pull request #521
Opened 2022-09-22 19:26 UTC by js-goupil

### WHY are these changes introduced?

This PR adds the appId to the mobile QR code generated for POS. The appId is required for certain APIs that POS makes available to UI extensions. In a dev environment, this is the only way for POS to access the appId for a dev app.

### WHAT is this pull request doing?

It checks to make sure the app exists, and if so adds the appId in the URL QR code.

### Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible [documentation](https://shopify.dev) changes
- [ ] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

2022-09-22 21:59 UTC, heltisace approved these changes
LGTM

2022-09-22 23:54 UTC, vividviolet requested changes

2022-09-22 23:54 UTC, vividviolet commented on packages/ui-extensions-dev-console/src/QRCodeModal/QRCodeModal.test.tsx
> +      `com.shopify.pos://pos-ui-extensions?url=${extension.development.root.url}&appId=${app.id}`,
I don't think this is safe to use - the only field that's guaranteed to be populated currently is the `app.apiKey`

2022-09-23 11:03 UTC, js-goupil commented
@vividviolet interesting. @henrytao-me do you know how Shopify mobile gets the appId? The reason why we need this is because the adminGenerateSession endpoint requires the app ID as a parameter. So as we're writing out the API for the app extension to be able to call that, we're trying to figure out a way to get that app ID in the dev environment.

2022-09-23 13:59 UTC, closed without merging