Fix dev breakage when missing capabilities fields
Shopify/cli pull request #575
Opened 2022-10-04 20:51 UTC by dmhenry

Co-authored-by: Richard Powell <richard.powell@shopify.com>

### WHY are these changes introduced?

Fixes #573 

When `shopify.ui.extensions.toml` doesn't include a `capabilities` clause, the browser reports the following error:

```
vendors~app.latest.en.e5376343c5580b97aa7a.js:2 TypeError: Cannot read properties of undefined (reading 'networkAccess')
    at app.latest.en.280faa0996ccd0490853.js:1:183003
    at Array.map (<anonymous>)
    at app.latest.en.280faa0996ccd0490853.js:1:182862
````

### WHAT is this pull request doing?

This PR sets default values for `capabilities` and `capabilities.network_access` and `capabilities.blocks_progress`. Because omitting any of the defaulted fields in tests is regarded as a syntax error, there is no way I can see to write unit tests.

### How to test your changes?

### Post-release steps

### Measuring impact

How do we know this change was effective? Please choose one:

- [x] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
- [ ] Existing analytics will cater for this addition
- [ ] PR includes analytics changes to measure impact

### Checklist

- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [ ] I've considered possible [documentation](https://shopify.dev) changes
- [ ] I've made sure that any changes to `dev` or `deploy` have been reflected in the [internal flowchart](https://www.figma.com/file/7vqUp50u6dm48Zfb4JRRn8/CLI3-Internals).

2022-10-04 21:07 UTC, isaacroldan approved these changes

2022-10-04 21:15 UTC, vividviolet requested changes
Can we verify that setting these defaults don't break deploys? Is the issue only occurring in local development? Is this a new issue or has it always been a problem? Does Checkout return a default config for capabilities when it's missing in the extension through GraphQL? If so, we should make the Dev Server follow suit but not mutate the actual config that gets sent to Core.

I just want to get down to the root cause. I thought capabilities is optional.

2022-10-05 09:47 UTC, isaacroldan commented
> Can we verify that setting these defaults don't break deploys? 

Tried adding a subscription-ui and deploy worked

> Is the issue only occurring in local development? Is this a new issue or has it always been a problem? 

Only happens with the new Node flow, Go works fine because [it adds some fields](https://github.com/Shopify/cli/blob/main/packages/ui-extensions-go-cli/core/core.go#L73) to the config by default
Should this be the default behavior for Node too instead of this fix to the schema?

> Does Checkout return a default config for capabilities when it's missing in the extension through GraphQL? If so, we should make the Dev Server follow suit but not mutate the actual config that gets sent to Core.

Yes, it does. I think it makes sense that the dev-server automatically sets these capabilities if they are not present. But not modify what we read from the toml.

2022-10-05 09:50 UTC, isaacroldan commented
Since this only affects the node flow, i'd say is not urgent. @dmhenry Could we update this so that the Node server does the same as the Go one?

2022-10-05 14:30 UTC, isaacroldan commented
I think we shouldn't add defaults to the schema, because that schema will be used both for dev and deploy. If we want the `dev` server to include defaults that should be done in the server itself, what do you think?

2022-10-05 15:18 UTC, vividviolet commented
> I think we shouldn't add defaults to the schema, because that schema will be used both for dev and deploy. If we want the `dev` server to include defaults that should be done in the server itself, what do you think?

I agree that it's safest to include defaults in the dev server itself instead of modifying the real configs

2022-10-06 12:55 UTC, merged